### ISSUE TITLE
Unity does not generate .sln files for project

### ISSUE THREAD

**Issue by michelmohr** [oculus-samples/Unity-Discover#1]
I can't seem to get .sln files generated for this project.
This makes it very hard to explore the code properly.

Opened the project using Unity 2022.2.21 and using visual studio community 2017 on Windows 10. Never experienced this issue before.

**Comment by jasonmeisel** [comment]
Thanks for the report! This issue you're having is that the project doesn't include the Visual Studio package by default. You can install the package using the Package Manager in Unity.

**Comment by michelmohr** [comment]
That solves the problem thank you. I was not aware there was such a thing as Visual Studio Code, and that it differed from regular Visual studio.
