### ISSUE TITLE
Objects in colocation don't apear in the same space in a room.

### ISSUE THREAD

**Issue by Tony-j77** [oculus-samples/Unity-Discover#12]
I'm trying the default mountain bike app on 2 Quest 3s and the shared spatial anchors are not aligned. The bike appears to be in different places for both users. I am using the 'host' and 'join' buttons and not the join in a separate room. Am I doing something wrong?

**Comment by AlexThiv** [comment]
Hi @Tony-j77,

When each user is done with the colocation step, do you see the anchor in the same physical location? Just to make sure also, you don't see the other user as an avatar right?

If you can provide the logs of both devices that would be helpful. Thanks
`adb logcat -s Unity`

**Comment by Tony-j77** [comment]
Hello @AlexThiv, I played around with the sample again and it seems like it doesn't matter if I press 'join' or 'join remotely', I always get sent into the room remotely i.e. "joined remotely". Also, yes, I do see the other user as an avatar. 

Here's my process: In headsest 1, I enter a room name, then click 'host', then I see "colocation ready". In headset 2, I enter the same room name, I click "join" ... but it says "joined remotely". Is there something immediately noticeable that I am doing wrong? If there isn't, I'll get the logs to you asap.

**Comment by AlexThiv** [comment]
Ok that means that the shared anchor was either not localized (didn't find that the 2 users were in the same room) or that the first user failed to share the shared spatial anchor.

Can you check that you accepted the permission to share the anchor and spatial data to the cloud?
Settings -> Apps -> Permissions -> Spatial Data

**Comment by AlexThiv** [comment]
Hi @Tony-j77, I did some additional digging and figured out what is the issue you are running into.
The scene loading requires an apk to be uploaded to App dashboard (where you do the configuration and get the AppId). Once the apk is uploaded and you have a subsequent build with the name application identifier the feature will work.

But we recently added a Scene feature flag for the android manifest and enabling that updating the manifest works without having to push and apk. You can see how we enabled it in this latest [commit](https://github.com/oculus-samples/Unity-Discover/commit/eda7d54baf18362b286acae4b21e7cb26bb4d254).

If you get the latest it should fix your issue. Thanks again for raising this.

**Comment by MunzeKonza93** [comment]
Hi @AlexThiv , i currently am experiencing the same described issue.
I build the Discover scene and sideloaded to a Quest 3 and Quest 2. I am able to host e.g. with quest 3 and join with Quest2 the same room. But everytime it joines remotely instead as colocation.

So i see the other players avatar (Grey Avatar not the Meta Avatar), and the anchor point is not at the same location.

Things i allready done:
* Permission for spatial data checked
* Created a new App in the Meta App Dashboard and copied the App ID into the configuration in Unity.
* Checked that both headsets are in the same Wifi.

A little help to figure out the problem would be very much appreciated :)

Thanks in advance :)

**Comment by AlexThiv** [comment]
@MunzeKonza93 can you verify in the logs if the application is entitled. If you have a unity log that says the app is not entitled, make sure to add both users to the organization. 
If that still doesn't work, try uploading a first apk to the Meta App Dashboard and make sure both users can go to the product page (PDP button on Overview page) and get the app.

**Comment by BlackFox16** [comment]
Hi,
I'm currently trying this with remote spaces. When placing the anchors in a specific room and launching as host, it ignores the anchor from the client, so as client I end up in the host's room and my anchor is not aligned. I would like to keep the anchor in my client space where it is. Any advice on how I can align these two anchors, even though the scene model is not the same? 

Thanks:)

**Comment by MunzeKonza93** [comment]
@AlexThiv  i checked last few days documentation about seting up shared spatial anchor and did everything from the docu:

* Signed App
* Added to the Developer Hub as Alpha Release Channel
* Added Useres to the App
* App is entitled
* Data Use Checkup setted up

Now When Starting Discover on both devices Quest 2 and Quest 3 i can see the Meta Avatar of the other User **but still Colocation is not working.**

I also installed the Discover Sample directly from the App Lab from the Devs and with that Version i also have the same problem.

So still no solution for this issue. Maybe its not compatible btw. Quest 3 and Quest 2 ?

Regards
