### ISSUE TITLE
Adjusting Scene Anchors Transform

### ISSUE THREAD

**Issue by B14ckFox** [oculus-samples/Unity-Discover#13]
Hello,

I am developing a project in Unity designed for the Meta Quest 3. My query is regarding the process of adjusting the transform properties (position, rotation, scale) of a scene model and how it translates from Unity to the Meta Quest 3 environment.

## Specific Questions:

Unity Adjustments: Is it possible to adjust the scene anchors (SceneVolume, ScenePlane) transform properties within Unity which can then be loaded by the Meta Quest 3 device or is the transform adjustments only achievable during the standalone scene setup process on the Meta Quest 3 device itself? In other words, I did a manual adjustment during the setup process and now I want to fine tune the room layout more accuratly in unity. Is this possible? If not any idea for a workaround?

Thank you for your assistance.

**Comment by AlexThiv** [comment]
Hi @B14ckFox,
What I understand from your question is that you do the manual room layout from the headset and then your application loads the scene. And then you want to update these scene anchors from within your application? (Let me know if I am miss understanding)

Once the elements are loaded in Unity you can interact with them however your application decides. You can apply scale, offset and rotation to the children of the anchors. I think what you would want is to load a prefab for you planes and volumes that have children that can be modified. The root will have the SceneAnchor and will always follow the detected position in the physical room, but the you can fine tune the children to better match your room.

Let me know if that helps or if there is still some questions remaining.

**Comment by B14ckFox** [comment]
Hi @AlexThiv ,

Okay, I'll try to formulate it a bit differently. So, my current setup involves two different rooms. When I start the session as the host, the scene model with its spatial anchors is loaded. Then, when a client joins this session, the SceneVolume and ScenePlane from the host room are shared over the network with the client. In the current setup, when checking in the Unity Editor for the client, I can only see the scene model data from the host, but not the scene model from the client. Do you have any advice on how to also load the client's scene model with its spatial anchors in the same networking session? When both are loaded, then I can proceed with further processing as you have described.
