### ISSUE TITLE
Project import error, unable to download several packages, very troublesome

### ISSUE THREAD

**Issue by zlggithubzlg** [oculus-samples/Unity-Discover#17]
Project import error, unable to download several packages, very troublesome

**Comment by jasonmeisel** [comment]
Hello, thanks for the report! Could you please provide us with the logs from the Unity Editor?

**Comment by zlggithubzlg** [comment]
[Editor.log](https://github.com/oculus-samples/Unity-Discover/files/14716152/Editor.log)
![image](https://github.com/oculus-samples/Unity-Discover/assets/116938548/72be2d52-b0f4-4008-b9ea-fa277ae2ab8f)
![image](https://github.com/oculus-samples/Unity-Discover/assets/116938548/08228fe3-863f-43cc-b84b-9e80a8f7f210)

**Comment by zlggithubzlg** [comment]
Thank you for your reply
