### ISSUE TITLE
Colocation does not work after following Configuration instructions

### ISSUE THREAD

**Issue by zhouaea** [oculus-samples/Unity-Discover#19]
In order to use colocation and make sure objects were correctly synced, not only did I have to make sure that **Share Point Cloud Data** and **Spatial Data** were enabled, I also had to upload a test apk to the meta quest app manager and add test users to the build. After that, I could build and run directly from Unity onto my Quest 3s and get colocation to work correctly. 

I followed the instructions listed [in this forum](https://communityforums.atmeta.com/t5/Unity-VR-Development/Spatial-Anchors-issues-and-quot-tutorial-quot/m-p/1037403/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExGSUxCUk5DNlI1OFRGfDEwMzc0MDN8U1VCU0NSSVBUSU9OU3xoSw#M21758%5C) thanks to the thread in #12.

**Comment by AlexThiv** [comment]
We updated the documentation to mention that an apk needs to be uploaded to use certain features like shared spatial anchors.
https://github.com/oculus-samples/Unity-Discover/blob/main/Documentation/Configuration.md#upload-to-release-channel

Thanks for bringing this up.
