### ISSUE TITLE
The issue of not using point cloud sharing。

### ISSUE THREAD

**Issue by zlggithubzlg** [oculus-samples/Unity-Discover#20]
Can spatial anchor data be stored in a private cloud and shared with other users? I mean point cloud sharing without Oculus

**Comment by jasonmeisel** [comment]
This is not possible with our current SDKs. Is there a use case you would need that capability for?

**Comment by zlggithubzlg** [comment]
Yes, due to the project, we can only use the LAN server to do multi-party collaborative MR, and we cannot access the external network. However, we have purchased more than 20 sets of quest3, which is very annoying, and I hope it can be changed

**Comment by jasonmeisel** [comment]
Unfortunately, we do not support that scenario with the current SDK. Thanks for letting us know this would be useful.
