### ISSUE TITLE
Is there any way to share scene data?

### ISSUE THREAD

**Issue by jianh1986** [oculus-samples/Unity-Discover#22]
I have three devices（Quest 3）, they are worked in a same physical space, and one of them scaned the physical space. Do I have to use other devices scan this physical space in order to be determined that three devices be in the same physical space? Is there a way to share the spatial data scanned by this device with other devices?

**Comment by AlexThiv** [comment]
Not at the device level at the moment. This is something that as been asked and we are aware of the interest for this feature.

The way discover shares that in the app, it will create a game object that represents each element on the host and shares it through networking to the clients. But this is all at the app level.
