### ISSUE TITLE
Error while opening the project

### ISSUE THREAD

**Issue by WahyuAgungBudiyanto** [oculus-samples/Unity-Discover#23]
Assets\Discover\Scripts\MenuActiveState.cs(3,16): error CS0234: The type or namespace name 'DroneRage' does not exist in the namespace 'Discover' (are you missing an assembly reference?)

Can someone help me? what is this error?

**Comment by jasonmeisel** [comment]
That's an odd error. Could you provide the [Editor.log](https://docs.unity3d.com/Manual/LogFiles.html) generated when opening the project?
