### ISSUE TITLE
Unable to add package [com.meta.xr.sdk.avatars@24.0.1]

### ISSUE THREAD

**Issue by Lancelot899** [oculus-samples/Unity-Discover#24]
[Package Manager Window] Error adding package: com.meta.xr.sdk.avatars@24.0.1.
Unable to add package [com.meta.xr.sdk.avatars@24.0.1]:
  Package [com.meta.xr.sdk.avatars@24.1.1] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by AlexThiv** [comment]
Hi @Lancelot899,

The error message seems odd has it's mentioning 24.0.1 as well as 24.1.1. Did you open the project without modifications to the manifest.json?

Can you check if you can get the Avatar package from the asset store  and see if that solves your issue after you click open in Unity 
https://assetstore.unity.com/packages/tools/integration/meta-avatars-sdk-271958

**Comment by AlexThiv** [comment]
We haven't been able to reproduce this. We will close this, but if you encounter it again please reopen with the additional details.
