### ISSUE TITLE
Issue with Controller driven hands when joining locally

### ISSUE THREAD

**Issue by Desvar** [oculus-samples/Unity-Discover#25]
We're encontering an issue when a second Player joins to the host room in local shared space mode (same wifi).
The second player test anchor (Prefabs/Colocation/TestAnchor) is spawned at the same place of the host player one and also his controller driven sinthetics hands are placed in that position. 
So when the second player moves his controllers, he see his hands far away from him.
In order to try to realign his controllers with his hands he must move itself to the original host player anchor position and try to force the Recenter with the controller oculus button.
If the second player leaves the controllers and the application switch to the hand-tracking, his real hands are correctly aligned with his synthetics virtual hands, but the moment he grab the controllers, they are still positioned far from him.

**Comment by AlexThiv** [comment]
Hi @Desvar, thanks for bringing this up. We fixed it by updating how the Interaction SDK is integrated by using the new OVRControllerDrivenHands. You can see the linked commit.
