### ISSUE TITLE
Implementing Dynamic occlusion via DepthAPI and upgrading to MRUK

### ISSUE THREAD

**Issue by carloposo** [oculus-samples/Unity-Discover#29]
Hello there,
I am using Discover as a starting point to build my own project. Specifically, I am using the MRBike as a reference.
I am trying to implement some sort of dynamic occlusion so that my spawned objects get occluded by my world's real objects.
If I am not mistaken, the only way to achieve this is via the Depth API, which requires Meta XR Core SDK v67.0.0 or above. This means, also, migrating from OVRSceneManager to MRUK. 

I am trying to upgrade Discover to use MRUK. Unfortunately, I am failing miserably as I am new to Unity and the Discover project is quite complex for a newbie.

I have some questions:
1. Are there any plans to release an updated version of Discover which uses MRUK?
2. Do you see any other ways to implement dynamic occlusion using this version of Discover?

Thank you!

**Comment by AlexThiv** [comment]
Hi @carloposo,
Thanks for bringing this up.
1. We are looking into updating to the latest SDK and migrating to MRUK, we don't have a set timeline at the moment.
2. In the mean time you can still use the deprecated OVRScene functions to unblock your update so that you can test the Dynamic occlusion via DepthAPI with the latest SDK.

**Comment by carloposo** [comment]
> What I mean is that you can update to SDK 67 or now 68 (latest) without changing to MRUK for the app to work. There will be some deprecation messages, and we recommend not shipping with these APIs, but if you want to be unblocked for Dynamic occlusion, you can keep the deprecated function while you test implementing occlusion.

Thank you, @AlexThiv 
I think I did that already and got few blocking issues. However, I'll try it once again.
Keep you posted.
C.

**Comment by AlexThiv** [comment]
Hi @carloposo,

We just released an update to use sdk v68 and use MRUK. Updating all deprecated functions.
I'll close this issue, feel free to open an new one if you have other issues.
