### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by AnantakSingh** [oculus-samples/Unity-Discover#3]
Building apk requires minimum android API Level 36 which hasn't been released yet.

**Comment by jasonmeisel** [comment]
Are you hitting an error when you try to make an Android build? If so, could you provide the error message?

I'm not seeing the issue myself, but it sounds like you may be having the same issue as [someone on the Unity forums](https://forum.unity.com/threads/update-android-sdk-36.1447801/). If so, try the solution in that thread (setting `AndroidTargetSdkVersion: 34` [in `ProjectSettings.asset`](https://github.com/oculus-samples/Unity-Discover/blob/main/ProjectSettings/ProjectSettings.asset#L168)).

**Comment by RiverExplorer** [comment]
MANY dependency errors. All are for pre released packages.
