### ISSUE TITLE
Strategy to upgrade my project the latest Discover (SDKs v68)

### ISSUE THREAD

**Issue by carloposo** [oculus-samples/Unity-Discover#30]
Hello,
so I have my project developed using the previous Discover release, prior to the release of the SDKs upgrades to v68.
What would be the preferred/suggested workflow to upgrade my project to the latest Discover release?
Thank you!
Carlo

**Comment by AlexThiv** [comment]
It depends how much changes you have and how it differs from where you original forked from. I have a couple of suggestions:

1. If you forked from this repo you might be able to pull and merge, there might be some merge conflicts but it should be manageable.
2. You can add this repo as a remote to your repo, git remote add, pull latest main and try to merge to your project, or Cherry pick each commit and fix issues.
3. You can create a patch and apply them to your project. Clone an additional copy of this repo and git diff > {patchFile}.patch and the git apply {patchFile}.patch
4. Comparing to the commits directly in here can also help.

In all cases depending on the changes you made from the original you might encounter conflicts. In code it shouldn't be too hard to address, if you have conflicts in scenes or prefabs, I would suggest you open a fresh clone of the project and compare the inspector side by side. We didn't modify many prefabs and they are core prefabs that you might not have updated either.

Let me know how it goes.

**Comment by carloposo** [comment]
Thank you @AlexThiv 
I might go for a fresh copy then. I'll keep you posted.

**Comment by carloposo** [comment]
@AlexThiv pulled a fresh new copy of the repo and rebuilt the project. It works nicely, thank you for updating it!
