### ISSUE TITLE
Connection failed: DisconnectedByPluginLogic

### ISSUE THREAD

**Issue by RXXING** [oculus-samples/Unity-Discover#33]
Hi everyonre,

hope you guys doing greate in the MR devekloping jorney. 

I was new to MR development and plan to discouver this Oculus Sample, but I cannot get it to run correctly on my PC. Since I can build the project and run as a single user so I think it is the "Photon Fusion" setting cause my error. 

I am get the error: Connection failed: DisconnectedByPluginLogic.

This is my first try to run this project so I didn't change other things rather than setting up the meta app id/ fusion ID/Voice ID

Please let me know what is going wrong, really appreciate. 

![Screenshot 2024-10-21 105659](https://github.com/user-attachments/assets/1ed8c1a3-39dc-4440-89a1-2a9abc803703)
![Screenshot 2024-10-21 105759](https://github.com/user-attachments/assets/6fb2bc89-4c14-4f0e-a58e-19a4d503a0f5)

**Comment by RXXING** [comment]
Just in case you get the same error....

For me, this is caused by the mismatch fusion version. I just created a new Fusion APP with fusion 1, and then it works.

**Comment by jasonmeisel** [comment]
Thank you for the report! Glad you were able to solve the issue.
