### ISSUE TITLE
Client can join room but app does not open

### ISSUE THREAD

**Issue by carloposo** [oculus-samples/Unity-Discover#36]
Hello,
thanks for helping me out with issue #35 
Client can now join room. 
I have created a new app, copying the MRBike and adjusting it to my needs.
Host can spawn it but client can't go past the icon.

I understand the client should get straight into the app (at least this is what it's happening with the MRBike app).

I attach the logcat of the client.

Thank you for your help.

[logcat2.txt](https://github.com/user-attachments/files/17797463/logcat2.txt)

**Comment by AlexThiv** [comment]
You are saying that the MRBike works as expected but your version of it doesn't, correct?
Does the components of your new app have network behaviours and are setup for networking? I'm asking because if they are networked then your client should see them spawn even if the app is not fully setup properly (like colocation not working).
If you don't see the network object of your new application, make sure that they are spawned properly using the fusion spawn functionality not just game object instantiate.

**Comment by carloposo** [comment]
Hello @AlexThiv 

A bit more info here. 
I copied/pasted the MRBike folder and renamed it as follows:

![Immagine 2024-11-19 095958](https://github.com/user-attachments/assets/902c25b6-52ac-4470-b5b9-eb10358a4e38)

I edited the scripts (just renamed some of them):

![Immagine 2024-11-19 100042 copy](https://github.com/user-attachments/assets/21509480-efc7-4210-a667-2376215fde8d)

...and changed the namespace to them all:

![Immagine 2024-11-19 101332](https://github.com/user-attachments/assets/b05df90f-fbe9-43d1-9c55-470f6907e54a)

Added my app to the manifests:

![Immagine 2024-11-19 100500](https://github.com/user-attachments/assets/725268bf-d8fb-4db0-bec3-02f830640184)

...and to the list:

![Immagine 2024-11-19 100522](https://github.com/user-attachments/assets/186ac9a4-3f3b-4465-a801-fdf5bcdf070a)

My app prefab looks pretty much like the MRBike one:

![Immagine 2024-11-19 102107](https://github.com/user-attachments/assets/f87b1e74-d1b5-4c88-a6ae-756ca80adf1b)

Also created my icon:

![Immagine 2024-11-19 102249](https://github.com/user-attachments/assets/30cec968-5bc9-4ec0-8f23-b1919d63b1e7)

So when my Client connects to the room, it sees my app's puck in the right position but the app does not start (whilst the MRBike app brings him straight into the scene). Clicking on the puck does not do anything. Am I missing something?

**Comment by AlexThiv** [comment]
Hi @carloposo,
Looking at this there isn't anything that seems wrong in your setup. I just did a simple test to see if I would run into the same issue and it all worked as expected. Could you try to do the same test and see if you run into the same issue? I did it directly from main.

1. Make a Copy of the BikeNetworkApplication prefab name C123NetwrokApplication
2. Open it and remove the BikeInteraction Child
3. Add a cube as a child of the prefab and Save
4. Regenerate Fusion Prefab tables 
![image](https://github.com/user-attachments/assets/221f921d-c93d-49d9-ba62-5ae576386ff8)
5. Make a copy of Configs/AppManifest/Bike to C123
7. Update the Unique name, Display Name and link the C123 NetApp prefab in AppPrefab 
![image](https://github.com/user-attachments/assets/2f726e65-e1af-4748-98e4-f7b1c9d14f84)
9. Add the AppManifest to the AppList
10. Run application for both Host and Client

Run the App on Host and Client, the app should launch for both and you can see the cube on the client and Host.

**Comment by carloposo** [comment]
Thanks @AlexThiv 
Your process worked for me, too.
So I thoroughly inspected my app and found out - my bad - some thing was missing here:

![Immagine 2024-11-20 142223](https://github.com/user-attachments/assets/593da1a3-08ee-47f2-91f4-ddcb26907ff0)

Now everything works as expected.

Thank you for your time!
Carlo
