### ISSUE TITLE
Not working via Link

### ISSUE THREAD

**Issue by eswaranand1997** [oculus-samples/Unity-Discover#7]
This sample does not work via Link at the moment

It seems that the entire presence SDK is not working via link. Scene features, local anchors, shared anchors, etc. The project throws the following errors
<img width="971" alt="image" src="https://github.com/oculus-samples/Unity-Discover/assets/78716202/d999f9fa-e3aa-4798-a80d-eac70860068e">

**Comment by AlexThiv** [comment]
Hi @eswaranand1997,
What is the flow that got you to this error?

Can you verify these settings in the Oculus App are toggled on:
Settings->Beta
- Developper Runtime Features
- Shared Point cloud over Meta Link

Even with these warnings, within the app if you press the menu button on the left controller and go to the last tab in the menu (scene settings) and enable the scene highlight do you see the scene?


Finally the highlighted warning seems to point out that it failed to localize a scene anchor, maybe you can try to redo your room setup in headset and test out link again once it's done.

Let me know how that goes. Thanks again for raising the issue.

**Comment by eswaranand1997** [comment]
Hi @AlexThiv 

Can confirm, all the beta settings are enabled including development runtime and sharing point cloud. 

Re-did room setup and no avail. When I do enable scene highlight, the walls and tables I created in room setup are loaded, but everything is located at the origin on top of each other (which makes sense as the error is saying it failed to localize/get the transform).

The same errors occur on the standard oculus asset samples for anchors, scene model, and shared anchors as well so I think this is an Oculus integration asset issue.

**Comment by AlexThiv** [comment]
Thanks for the additional information. It's something I've seen before that would normally be fixed by restarting link or redoing my room setup. But it doesn't seem to fix your issue. I'm asking internally if there is anything else that could cause this issue and I'll get back to you with my findings.

**Comment by eswaranand1997** [comment]
I confirmed with another user that they are seeing the same issue when running the Oculus anchor and room samples (they didn't try out discover specifically)

**Comment by AlexThiv** [comment]
Could you collect the logs from the Device? You can easily do that using [Meta Quest Developer Hub](https://developer.oculus.com/meta-quest-developer-hub/)
Navigate to **Device Manager** on the left navigation bar, then click **Device Logs** on the top right side.
Once the logs window is open start the application and you can either copy the logs or download them using the buttons on the bottom left of the log window.

We want to see if the device is giving us more information to track down the issue.

Also could you give us some info about what versions you are currently using.
Oculus App/ Meta Link App: Settings->General / all the way at the bottom
Headset: Settings->System->Software Update / Current Version Details / Version

**Comment by AlexThiv** [comment]
Hi, we just updated to the latest SDK v60.

We tested it with Oculus app 60, Headset 60 and this latest version and it's seems to be working.
I'll close this as we haven't gotten any update in a month, please open a new issue if you run in any problems.
