### ISSUE TITLE
No floor, cant start the apps from menu

### ISSUE THREAD

**Issue by ncabello2222** [oculus-samples/Unity-Discover#9]
When i run the apk in the headset i can connect to the photon server and open the menu, (i can see a second player conected) but when i grab any of the apps, the icon its in red and i cant put it  in the floor, its always red and i cant rotate it. Also i dont see any floor. This are some logs from unity after i build and run:

2023-12-11 22:29:08.207 2323 2347 Warn OpenGLRenderer Surface doesn't have any previously queued frames, nothing to readback from
2023-12-11 22:29:08.226 2323 2323 Error BLASTBufferQueue [ViewRootImpl[UnityPlayerActivity]#2](f:0,a:0) Applying pending transactions on dtor 1
2023-12-11 22:29:18.600 2323 2350 Error OVRPlugin [GetBoundaryGeometry] isSessionRunning == false (arvr/projects/integrations/OVRPlugin/Src/Util/CompositorOpenXR.cpp:11099)
2023-12-11 22:29:18.659 2323 2847 Error TREX Interface version 3 was not found. Check debug build for more information.
2023-12-11 22:29:34.111 2323 2350 Warn [CT] Anchor:SlamAnchorMemoryOSSDKClient: [Throttled count=574] Skipping invalid anchorHandle when attempting to cache AnchorStates
2023-12-11 22:29:43.926 2323 2350 Warn OsSdk Requested historical tracking state too far in the past; oldest: 11554.949799s, requested: 11554.673296s

**Comment by AlexThiv** [comment]
Do you see the walls and ceiling?

Pressing on the left controller menu button then selecting the right most tab (Scene Settings) can you toggle the scene highlight and send us a screen shot of what you see.

**Comment by ncabello2222** [comment]
When i toggle scene highlight nothing happens i dont see walls or ceiling.   I have the profile id and user id from the Data Use Checkup. I also have a keystore,  I uploaded to the meta developer hub and then installed in headset.
I realize in other template i am trying to build "Shared Spatial Anchors" after i installed i was getting  a log "user not allowed to use this app, oculus id:0  shared anchor will not work". So i am checking everything again. I invited myself in the apha chanel, but i am not sure how can i authenticate

**Comment by AlexThiv** [comment]
Did you have to upload an apk to get it working? This might be a step that is missing in our documentation actually, let us know if that was how you fixed your issue.

**Comment by ncabello2222** [comment]
The app mostly works, anchor and multiplayer, but still cant start the apps from the menu.

These are the steps i am following. Using Unirty version 2022.3.4f1
Set android as build target
Import the template, add the app id and photon id.
Create a keystore and passwords
Run oculus setup tool
In the developer i created an app and enabled Data Use Checkup as indicated (all are active)
Upload the app to the meta hub 
Added myself as test users for the apha build
I can see the app in device in the my oculus 
Install the app, mapped the room, conect to photon, then I can see the anchor in the floor. I see the message Colocation ready
In the menu I can pick both icons but it doesnt react to the floor nor the walls, its red all the time.
In the menu i can togle the highlight but nothing happens, i dont see the walls nor floor.
On the other hand  In the editor play mode works well, i can put the icons in the floor and start the apps.

Curious fact, a couple of days ago I started the original app, your original funcional app from the applab,  and had the same problem, but I restarted it and remapped the room and it worked fine.

**Comment by AlexThiv** [comment]
Hi,

We weren't able to reproduce what you are experiencing. It does seem like the room didn't load.

We just updated the repository to use our latest SDK v60. Could you test that out and let us know if you run into the same issue?

If you do could you send us the logs, we might get more info on why the room isn't loaded in there. You can get the logs using this command `adb logcat -s Unity`

**Comment by ncabello2222** [comment]
[odh_logs_2023-12-29 04.31.10.152.txt](https://github.com/oculus-samples/Unity-Discover/files/13790955/odh_logs_2023-12-29.04.31.10.152.txt)
I opened the app at 1:25 more or less and the test took 1 minute app. Same issue, conected and colocation ready with anchor, but after grabing the icon its red. Also when i check the option to show boundaries it doesnt show anything. 
The package name is com.nicolas.discovery and the name i gave the app is mrclassroom

**Comment by AlexThiv** [comment]
@ncabello2222 You can follow this https://developer.oculus.com/resources/publish-app-metadata/ to add icons and images for your app submission.
